# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names;
# file_template = %%(rev)s_%%(slug)s
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to use in generate-slug-length
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, initial revs will go to the first directory,
# and each subsequent rev will go to the same directory as the leaf it is based on
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; as above, this can be the default
# version_path_separator = os.pathsep

# the designation cleanup_how provides a policy for removing
# old versions after they are merged.
# cleanup_how = truncate

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@tip-postgres:5432/tip


[post_write_hooks]
# post_write_hooks allows scripts to be run after a revision is created.
# hooks are defined by providing a name and then setting the options.
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
