import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import List, Optional, Any
from pydantic import BaseModel, Field

from app.models.indicator import IndicatorType
from app.models.evidence import EvidenceType

class EnrichmentResult(BaseModel):
    """
    Standardized container for enrichment output.
    """
    indicator_id: uuid.UUID
    source_name: str
    evidence_type: EvidenceType
    raw_payload: dict = Field(default_factory=dict)
    confidence_delta: float = 0.0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    success: bool = True
    error_message: Optional[str] = None

class BaseEnricher(ABC):
    """
    Abstract base class for all enrichment providers.
    Every enricher must implement this interface.
    """

    @abstractmethod
    async def enrich(self, indicator_id: uuid.UUID, indicator_value: str) -> EnrichmentResult:
        """
        Perform the actual enrichment logic.
        """
        pass

    @abstractmethod
    def get_supported_types(self) -> List[IndicatorType]:
        """
        Returns a list of indicator types this enricher can handle.
        """
        pass

    @abstractmethod
    def get_source_name(self) -> str:
        """
        Returns the human-readable name of the enrichment source.
        """
        pass

    @abstractmethod
    def get_evidence_type(self) -> EvidenceType:
        """
        Returns the type of evidence generated by this enricher.
        """
        pass
